// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NM_UnGvJqWvkc5Yb4KRApLK2wZJcDbo',
    appId: '1:578763251594:web:e2e74e94dc1fefe1767273',
    messagingSenderId: '578763251594',
    projectId: 'test-40694',
    authDomain: 'test-40694.firebaseapp.com',
    storageBucket: 'test-40694.firebasestorage.app',
    measurementId: 'G-LYPPJRV5E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg1Xo1L6m0zTsbL9Fu9LnVO_hEO4hk1gs',
    appId: '1:578763251594:android:e007fb0cd2e40bab767273',
    messagingSenderId: '578763251594',
    projectId: 'test-40694',
    storageBucket: 'test-40694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnyOIY3fSZDLjwOqWNCOTWcZAoh-dhP28',
    appId: '1:578763251594:ios:7bd949b2497c017f767273',
    messagingSenderId: '578763251594',
    projectId: 'test-40694',
    storageBucket: 'test-40694.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnyOIY3fSZDLjwOqWNCOTWcZAoh-dhP28',
    appId: '1:578763251594:ios:7bd949b2497c017f767273',
    messagingSenderId: '578763251594',
    projectId: 'test-40694',
    storageBucket: 'test-40694.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9NM_UnGvJqWvkc5Yb4KRApLK2wZJcDbo',
    appId: '1:578763251594:web:e5ae9e89f613e49e767273',
    messagingSenderId: '578763251594',
    projectId: 'test-40694',
    authDomain: 'test-40694.firebaseapp.com',
    storageBucket: 'test-40694.firebasestorage.app',
    measurementId: 'G-8KTKTYHXRT',
  );
}
