// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD3D1w2g1NwXOeRnsWm-cpKobChtbZS7HQ',
//     appId: '1:979666961902:web:0f86fa77268f0dd4f8baff',
//     messagingSenderId: '979666961902',
//     projectId: 'test-60a7e',
//     authDomain: 'test-60a7e.firebaseapp.com',
//     storageBucket: 'test-60a7e.firebasestorage.app',
//     measurementId: 'G-PYSQQZGYNH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC5L3wV0fjziQRZsVDltQMlGPGKpWDDjx8',
//     appId: '1:979666961902:android:3207254cb4ed1e61f8baff',
//     messagingSenderId: '979666961902',
//     projectId: 'test-60a7e',
//     storageBucket: 'test-60a7e.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAGo-RdiztjRmGxv4hvs_DyQmtMJbcO7a8',
//     appId: '1:979666961902:ios:bec6f16d14afc5a7f8baff',
//     messagingSenderId: '979666961902',
//     projectId: 'test-60a7e',
//     storageBucket: 'test-60a7e.firebasestorage.app',
//     iosBundleId: 'com.example.flutterApplication1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAGo-RdiztjRmGxv4hvs_DyQmtMJbcO7a8',
//     appId: '1:979666961902:ios:bec6f16d14afc5a7f8baff',
//     messagingSenderId: '979666961902',
//     projectId: 'test-60a7e',
//     storageBucket: 'test-60a7e.firebasestorage.app',
//     iosBundleId: 'com.example.flutterApplication1',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD3D1w2g1NwXOeRnsWm-cpKobChtbZS7HQ',
//     appId: '1:979666961902:web:0f86fa77268f0dd4f8baff',
//     messagingSenderId: '979666961902',
//     projectId: 'test-60a7e',
//     authDomain: 'test-60a7e.firebaseapp.com',
//     storageBucket: 'test-60a7e.firebasestorage.app',
//     measurementId: 'G-PYSQQZGYNH',
//   );

// }