name: Flutter_CI_CD

on:
  # Runs this action when you push on main
  push:
    branches: [ "main" ]
  # Runs this when a PR against main is created
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:
    # Use Ubuntu for all Flutter build and Firebase upload tasks
    runs-on: ubuntu-latest

    steps:
      # Clones the project on the machine
      - uses: actions/checkout@v4

      # Sets up Java 17
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Installs Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Fetch project dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify formatting
      - name: Verify formatting
        run: dart format --output=none

      # Analyze source code
      - name: Analyze project source
        run: flutter analyze --fatal-warnings

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK
      - name: Build APK
        run: flutter build apk

      - name: Authenticate Firebase
        run: echo "${{ secrets.FIREBASE_TOKEN }}" > firebase.json && firebase login:ci --token $(cat firebase.json)
        
      # Upload APK to Firebase distribution
      - name: Upload APK to Firebase distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_TOKEN }}
          groups: all_testers
          file: build/app/outputs/flutter-apk/app-release.apk
